image: nixos/unstable
secrets:
  - 2b4ba51d-1195-420f-a561-002b6640b9fb
sources:
  - git@git.sr.ht:~dbalan/system-configuration
tasks:
  - setup: |
  - build: |
      for host in "kimchi" "v60"
      nixos-rebuild build --flake ".#{host}"
triggers:
  - action: email
    condition: failure
    to: 'Build Logs <build@dbalan.in>'
