image: nixos/unstable
secrets:
  - 2b4ba51d-1195-420f-a561-002b6640b9fb
sources:
  - git@git.sr.ht:~dbalan/system-configuration
tasks:
  - build: |
      cd system-configuration
      for host in "kimchi" "v60"; do
        nixos-rebuild build --flake ".#${host}"
      done
triggers:
  - action: email
    condition: failure
    to: 'Build Logs <build@dbalan.in>'
