{ config, pkgs, ... }:

# FIXME: Make a system specific pkg list.

let
  unstable = import <unstable> {};
  browsercat = import ./browsercat.nix {};
  kdepim = with pkgs; with kdeApplications; [ # KDE Apps
    akonadi
    akonadi-calendar
    akonadi-contacts
    akonadi-import-wizard
    akonadi-mime
    akonadi-notes
    akonadi-search
    akonadiconsole
    akregator
    ark
    breeze-icons
    breeze-qt5
    gwenview
    kaddressbook
    kalarm
    kalarmcal
    kate
    kcalutils
    kdepim-addons
    kdepim-apps-libs
    kdepim-runtime
    kdialog
    kidentitymanagement
    kldap
    kmail
    kmailtransport
    kmbox
    kmime
    kmix
    kontact
    kontactinterface
    konversation
    korganizer
    kpimtextedit
    libkdepim
    libksieve
    mailcommon
    messagelib
    okular
    oxygen
    oxygen-icons5
    oxygenfonts
    pim-sieve-editor
    pimcommon
    redshift-plasma-applet
    spectacle
    # End of KDE Apps
  ];
  unstablePackages = with unstable; [
    cabal-install
    ghc
    ghcid
    signal-desktop
    xow
    awscli2
    chrysalis
    signal-desktop
  ];  
  commonPackages = with pkgs; [
    # (pkgs.callPackage ./pipet.nix {})
    #(haskell.lib.justStaticExecutables (haskellPackages.callPackage ./idid.nix {}))
    #haskellPackages.arbtt
    ag
    alot
    anki
    ansible
    arandr
    awslogs
    bat
    beancount
    brave
    browsercat.packages."browser-cat"
    discord
    docker-compose
    dunst
    evince
    exa
    fava
    file
    firefox
    freerdp
    fzf
    gcc
    git-secret
    gitAndTools.hub
    gnome3.adwaita-icon-theme
    gnome3.meld
    gnome3.seahorse
    gnumake
    go
    godef
    gopass
    handbrake
    htop
    httpie
    imagemagick
    isync
    jq
    ldns
    libqalculate
    libsecret
    llvmPackages.bintools
    manpages
    mpv
    msmtp
    neomutt
    nload
    nmap_graphical
    notmuch
    okular
    p7zip
    pandoc
    pcmanfm
    python38Full
    python38Packages.ipython
    python38Packages.poetry
    python38Packages.qrcode
    python38Packages.virtualenv
    rambox
    rdesktop
    restic
    ripgrep
    rsync
    shutter
    skypeforlinux
    steam
    stylish-haskell
    sublime-music
    taffybar 
    tcpdump
    telnet
    thunderbird
    tmux
    tmux-cssh
    tree
    unzip
    vulkan-tools
    wineWowPackages.full
    xmobar
    xorg.xhost
    zathura
    zeal
    zoom-us
  ];
in
{
  home.packages = commonPackages ++ unstablePackages ++ kdepim;
}
    
